### ISSUE TITLE
Add Thymeleaf Nature only works for Java Projects

### ISSUE THREAD

**Issue by delinius** [thymeleaf/thymeleaf-extras-eclipse-plugin#40]
I couldn't get the content assist to work, but fortunately I found issue #25 where you explain how to debug eclipse plugins. Doing this I found out that when I execute "Add Thymeleaf Nature" on my web project I get this Exception:

Caused by: java.lang.ClassCastException: org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.jdt.core.IJavaProject at org.thymeleaf.extras.eclipse.nature.AddThymeleafNatureAction.execute(AddThymeleafNatureAction.java:47)
etc.

So I changed my project to a plain Java project and voilá: it works. This is unfortunate since I guess everybody developing Thymeleaf templates is doing so in some kind of web project. Apart from that: thanx for developing the plugin.

Workaround: add java nature to <natures> in .project:
<nature>org.eclipse.jdt.core.javanature</nature>

**Comment by ultraq** [comment]
That's strange.  A web project extends Java project, so what you did should have been OK.  Question: was your web project a 'Dynamic Web Project', created by the Eclipse WTP plugin? (eg: New Project >> Web >> Dynamic Web Project)

**Comment by delinius** [comment]
I started with the project supplied by breadleaf (eCommerce platform that uses Thymeleaf), then I tried creating a new dynamic web project and a static web project using New Project etc. Eclipse Kepler btw. I'll try to reproduce it when my schedule allows.

**Comment by tduchateau** [comment]
Hi!

I'm re-testing the v2.0.3 with Eclipse Kepler.

Details:
- Eclipse Java EE IDE for Web Developers.
- Version: Kepler Service Release 1
- Build id: 20130919-0819
- java.version=1.6.0_34

I'm facing the same issue as [before](https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/issues/42#issuecomment-27170039) and as @delinius (see the full stacktrace at the bottom).

Reproduced by (EDIT: I added all the existing natures associated with each project):
- adding a new Project => seems normal
- adding a new Java Project
  
  `<nature>org.eclipse.jdt.core.javanature</nature>`
- adding a new Dynamic Web Project (WTP)
  
  `<nature>org.eclipse.jem.workbench.JavaEMFNature</nature>`
  `<nature>org.eclipse.wst.common.modulecore.ModuleCoreNature</nature>`
  `<nature>org.eclipse.wst.common.project.facet.core.nature</nature>`
  `<nature>org.eclipse.jdt.core.javanature</nature>`
  `<nature>org.eclipse.wst.jsdt.core.jsNature</nature>`
  `<nature>org.zeroturnaround.eclipse.jrebelNature</nature>`
- adding a new Maven Project (using the M2E wizard)
  
  `<nature>org.eclipse.jem.workbench.JavaEMFNature</nature>`
  `<nature>org.eclipse.wst.common.modulecore.ModuleCoreNature</nature>`
  `<nature>org.eclipse.jdt.core.javanature</nature>`
  `<nature>org.eclipse.m2e.core.maven2Nature</nature>`
  `<nature>org.eclipse.wst.common.project.facet.core.nature</nature>`
  `<nature>org.eclipse.wst.jsdt.core.jsNature</nature>`
  `<nature>org.zeroturnaround.eclipse.jrebelNature</nature>`
- importing an existing Maven Project (still with M2E)
  
  `same as with new Maven Project`

The full stacktrace:

```
org.eclipse.e4.core.di.InjectionException: java.lang.ClassCastException: org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.jdt.core.IJavaProject
at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:63)
at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:243)
at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:224)
at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:167)
at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:850)
at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:743)
at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:727)
at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:662)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
Caused by: java.lang.ClassCastException: org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.jdt.core.IJavaProject
at org.thymeleaf.extras.eclipse.nature.AddThymeleafNatureAction.execute(AddThymeleafNatureAction.java:47)
at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
```

Let me know if I can be of any help!

Regards,
Thibault

**Comment by ultraq** [comment]
So do all of those scenarios reproduce the error for you?

Unfortunately I haven't been able to reproduce this error at all :(  I tried importing Maven projects as in the other issue, but it still seems to go fine.  I can only guess at what might be happening on other computers, which is that for some reason the selected project cannot be coerced into a Java project (there's a cast on the line in the stack trace, [AddThymeleafNatureAction.java:47](https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/blob/2.0-master/bundles/thymeleaf-extras-eclipse-plugin.core/src/main/java/org/thymeleaf/extras/eclipse/nature/AddThymeleafNatureAction.java#L47) that assumes that the selection is an IJavaProject type).

Are you able to set up your computer to debug the Eclipse plugin again, then put a breakpoint at that line to tell me what the types of items inside the `selectedprojects` variable _actually_ are?

**Comment by tduchateau** [comment]
> So do all of those scenarios reproduce the error for you?

Unfortunately yes :-(

> Are you able to set up your computer to debug the Eclipse plugin again, then put a breakpoint at that line to tell me what the types of items inside the selectedprojects variable actually are?

Sure, I'll try as soon as I can. I'll keep you posted in this issue.

**Comment by pawelantczak** [comment]
Do we have any update on this?

**Comment by tduchateau** [comment]
For my part, unfortunately I didn't had time to go into details :-(

**Comment by pawelantczak** [comment]
I'm playing around with this plugin, and to be honest, I even can't add nature to fresh, empty, plain java project. Looking forward for fix.

**Comment by ultraq** [comment]
If you're having trouble finding the time @tduchateau, then I'll go ahead with a 'guess fix' as to what might be going on, adding a helluva lot of logging around the affected area just in case.  I wish I knew what exactly is going on though, and why I can't replicate it on any of my Eclipse installs.

**Comment by tduchateau** [comment]
Hi,

I just found out that in my workspace, the selected project is already an instance of `IProject`, causing the above exception.
I tested the following fix and it works great.

```
/**
 * {@inheritDoc}
 */
@Override
public Object execute(ExecutionEvent event) {

    IEvaluationContext context = (IEvaluationContext)event.getApplicationContext();
    Collection<?> selectedProjects = (Collection<?>) context.getDefaultVariable();
    List<IProject> projects = new ArrayList<IProject>();

    // Cycle through the context variables to retrieve typed projects
    for (Object selectedProject : selectedProjects) {
        if (selectedProject instanceof IProject) {
            IProject project = (IProject) selectedProject;
            projects.add(project);
        } else if (selectedProject instanceof IJavaProject) {
            IJavaProject javaProject = (IJavaProject) selectedProject;
            projects.add(javaProject.getProject());
        }
    }

    // Add the Thymeleaf nature to all selected projects
    for (IProject project : projects) {
        try {
            IProjectDescription description = project.getDescription();
            String[] natures = description.getNatureIds();
            String[] newnatures = new String[natures.length + 1];
            System.arraycopy(natures, 0, newnatures, 0, natures.length);
            newnatures[natures.length] = ThymeleafNature.THYMELEAF_NATURE_ID;
            description.setNatureIds(newnatures);
            project.setDescription(description, null);
        } catch (CoreException ex) {
            // Do nothing
        }
    }

    return null;
}
```

If you prefer, I can make a PR.

Regards,
Thibault

**Comment by ultraq** [comment]
A pull request would be awesome :+1:   Thanks again for your help with the plugin.

**Comment by tduchateau** [comment]
OK! Against what branch?

**Comment by ultraq** [comment]
2.1-dev please.  I'll cherry pick it for the 2.0 branches as well if I need to bring it to the 2.0 versions of the plugin.
