### ISSUE TITLE
Can't Add Thymeleaf Nature to Project

### ISSUE THREAD

**Issue by Chropez** [thymeleaf/thymeleaf-extras-eclipse-plugin#42]
I Installed the plugin through the update-site and I'm running the latest Kepler.

When I try to Add Thymeleaf Nature to my project I get an Error : Unhandled event loop exception.

I've also tried adding Thymeleaf Nature to a clean new Dynamic Web Project.

Exception Stack Trace:

```
org.eclipse.e4.core.di.InjectionException: java.lang.ClassCastException: org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.jdt.core.IJavaProject
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:63)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:243)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:224)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:167)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:850)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:743)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:727)
    at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:662)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4170)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
Caused by: java.lang.ClassCastException: org.eclipse.core.internal.resources.Project cannot be cast to org.eclipse.jdt.core.IJavaProject
    at org.thymeleaf.extras.eclipse.nature.AddThymeleafNatureAction.execute(AddThymeleafNatureAction.java:47)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
    at sun.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    ... 37 more
```

**Comment by ultraq** [comment]
Related to #40, possible duplicate.

**Comment by tduchateau** [comment]
Hi!

Just reproduced the same issue on a Kepler installation.
Note that all the projects in the current workspace have been imported as "Existing Maven project" (with the M2E plugin)

Regards,
Thibault

**Comment by ultraq** [comment]
I'm having trouble reproducing this.  I don't exactly have Maven web apps lying around, so what I've tried is to clone the Thymeleaf example projects (gtvg and petclinic ones), import them as Existing Maven Projects, then apply the Thymeleaf nature, and it works every time :|  I've also tried creating brand-new Dynamic Web Projects and they work fine too.

@tduchateau do you have a Maven web app out there I can try that doesn't work for you?

**Comment by tduchateau** [comment]
Sure, you can give a try with the Dandelion-datatables Thymeleaf sample: https://github.com/dandelion/dandelion-samples/tree/master/datatables-thymeleaf

**Comment by ultraq** [comment]
Darnit, that worked just fine too.  I've just noticed I'm not running the latest Kepler SR1, and it is about time I cleaned-up my Eclipse installation (I'm wondering if something in there is preventing me from reproducing this bug), so I'll start from scratch with the latest Eclipse and give it another try.
