### ISSUE TITLE
content assist doesn't seem to work

### ISSUE THREAD

**Issue by alagenchev** [thymeleaf/thymeleaf-extras-eclipse-plugin#51]
I installed the thymeleaf plugin from the update site. added this to my html file: 
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
and even added the thymeleaf nature to the project. Content assist doesn't work and I'm getting the following error in the error log: 
"Unable to execute XPath expression"

with this stack trace:

java.io.FileNotFoundException: /Users/ialagenchev/ivan/eclipse/Eclipse.app/Contents/MacOS/rmi.dtd (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at java.io.FileInputStream.<init>(FileInputStream.java:101)
    at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
    at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
    at org.apache.xerces.impl.XMLEntityManager.startEntity(Unknown Source)
    at org.apache.xerces.impl.XMLEntityManager.startDTDEntity(Unknown Source)
    at org.apache.xerces.impl.XMLDTDScannerImpl.setInputSource(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentScannerImpl$DTDDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
    at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:298)
    at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:328)
    at org.thymeleaf.extras.eclipse.dialect.ProjectDependencyDialectLocator.isDialectHelpXMLFile(ProjectDependencyDialectLocator.java:109)
    at org.thymeleaf.extras.eclipse.dialect.ProjectDependencyDialectLocator.access$0(ProjectDependencyDialectLocator.java:99)
    at org.thymeleaf.extras.eclipse.dialect.ProjectDependencyDialectLocator$1.call(ProjectDependencyDialectLocator.java:163)
    at org.thymeleaf.extras.eclipse.dialect.ProjectDependencyDialectLocator$1.call(ProjectDependencyDialectLocator.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
--------------- linked to ------------------
javax.xml.xpath.XPathExpressionException
    at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:301)
    at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:328)
    at org.thymeleaf.extras.eclipse.dialect.ProjectDependencyDialectLocator.isDialectHelpXMLFile(ProjectDependencyDialectLocator.java:109)
    at org.thymeleaf.extras.eclipse.dialect.ProjectDependencyDialectLocator.access$0(ProjectDependencyDialectLocator.java:99)
    at org.thymeleaf.extras.eclipse.dialect.ProjectDependencyDialectLocator$1.call(ProjectDependencyDialectLocator.java:163)
    at org.thymeleaf.extras.eclipse.dialect.ProjectDependencyDialectLocator$1.call(ProjectDependencyDialectLocator.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.io.FileNotFoundException: /Users/ialagenchev/ivan/eclipse/Eclipse.app/Contents/MacOS/rmi.dtd (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at java.io.FileInputStream.<init>(FileInputStream.java:101)
    at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
    at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
    at org.apache.xerces.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
    at org.apache.xerces.impl.XMLEntityManager.startEntity(Unknown Source)
    at org.apache.xerces.impl.XMLEntityManager.startDTDEntity(Unknown Source)
    at org.apache.xerces.impl.XMLDTDScannerImpl.setInputSource(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentScannerImpl$DTDDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
    at com.sun.org.apache.xpath.internal.jaxp.XPathExpressionImpl.evaluate(XPathExpressionImpl.java:298)
    ... 9 more

**Comment by tduchateau** [comment]
Take a look at @ultraq's anwers here: #47

**Comment by alagenchev** [comment]
@tduchateau, so the solution is to do a git pull and build the plugin myself?

**Comment by tduchateau** [comment]
I'd say yes, even if I didn't test it yet :-)

**Comment by alagenchev** [comment]
how does one build the plugin? I saw a build.gradle file, but doing gradle build, doesn't work.

**Comment by ultraq** [comment]
The plugin is built using Maven - there's the main pom in the root directory, and a bunch of sub-projects inside the bundles, features, and repository directories.  I think you can just use `mvn install` to get it to build.  That'll create a zip file of the Eclipse plugin inside a `target/repository` directory off the root directory.

**Comment by alagenchev** [comment]
@ultraq thank you! That fixed the problem for me.
