### ISSUE TITLE
Update site returns 404

### ISSUE THREAD

**Issue by martin-spa** [thymeleaf/thymeleaf-extras-eclipse-plugin#59]
The update site specified in the readme (http://www.thymeleaf.org/eclipse-plugin-update-site/) is not working.

**Comment by ultraq** [comment]
Did you enter that URL into Eclipse as an update site URL (eg: when trying to install a plugin or search for plugins to install), or try to got to the URL in your browser? Using it in Eclipse will work, but using it in your browser will give the 404.

(Copied from #58)

**Comment by martin-spa** [comment]
I have this message: 
![image](https://cloud.githubusercontent.com/assets/1262604/4384799/17b05ab6-43bc-11e4-9d17-86480fec4d02.png)

Here's the message from the .log file in the workspace:

```
!MESSAGE Unable to read repository at https://sourceforge.net/projects/thymeleaf/files/thymeleaf-extras-eclipse-plugin/2.1.1/update-site/content.xml.
!STACK 0
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1917)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:301)
    at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:295)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1369)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:156)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:925)
    at sun.security.ssl.Handshaker.process_record(Handshaker.java:860)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
    at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
    at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
    at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
    at org.eclipse.ecf.provider.filetransfer.browse.URLFileSystemBrowser.runRequest(URLFileSystemBrowser.java:113)
    at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
    at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
    at sun.security.validator.Validator.validate(Validator.java:260)
    at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
    at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
    at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
    at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1351)
    ... 13 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
    at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
    ... 19 more
```

Note: Eclipse version is Kepler Service Release 2, running on Java 8.

**Comment by brushmate** [comment]
I have the same issue.

**Comment by ultraq** [comment]
Unfortunately I can never replicate this issue.  The site is hosted on GitHub, and it's not always the most reliable for content delivery in this manner.  Are you able to access one of the Eclipse files at the update site in your browser when it gives you the 404?  eg: http://www.thymeleaf.org/eclipse-plugin-update-site/p2.index (browser may ask you to download a file, but you don't need to).

**Comment by brushmate** [comment]
I tried to add the update site on my personal machine and there it works. So I think it is an network configuration issue at work. I am behind a proxy and I think this causes the issue.

**Comment by brushmate** [comment]
I think the problem was that I am behind a NTLM proxy server. I solved the problem by setting up a local ntlm proxy using Cntlm. This proxy injects missing authentication information into requests and forwards it to the real proxy. Then I set up eclipse to use my local proxy. Now I am able to install the plugin. However it is strange that other update sites have been working before and the install process took very long (more than 5 minutes).

**Comment by rkand4** [comment]
Guys looks like this is still an issue and what I find the best link so far is http://sourceforge.net/projects/thymeleaf/files/thymeleaf-extras-eclipse-plugin/2.1.1/update-site/   now  it should work hoping you have access to sourceforge downloads without any firewall issues or things like that. Thanks !

**Comment by amelnikoff** [comment]
@rkand4 same problem for me, only direct url to springsource is working
